### PR TITLE
Add missing import in external package test

### PR DESCRIPTION
**Pull request by inkel**
This pull request adds the missing import found in #43.

(I eventually figured out how to use `embedmd`, nice tool!)

### CODE REVIEW

**Comment by inkel** [comment]
I singed it!

**Comment by inkel** [comment]
Ah, you have tests on the files, awesome 😸 

It obviously fails because the change is adding an import path that isn't being used. I've come up with two solutions:

```diff
 3-dynamic-analysis/2-testing/sum/sum_test.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/3-dynamic-analysis/2-testing/sum/sum_test.go b/3-dynamic-analysis/2-testing/sum/sum_test.go
index 6475a09..525e5f5 100644
--- a/3-dynamic-analysis/2-testing/sum/sum_test.go
+++ b/3-dynamic-analysis/2-testing/sum/sum_test.go
@@ -17,7 +17,7 @@ package sum_test
 import (
 	"testing"
 
-	"github.com/campoy/go-tooling-workshop/3-dynamic-analysis/2-testing/sum"
+	. "github.com/campoy/go-tooling-workshop/3-dynamic-analysis/2-testing/sum"
 )
 
 func TestAll(t *testing.T) {
```

I like this one, but I don't recall you explaining the meaning of importing a path as `.` in this workshop, so people might get lost.

```diff
 3-dynamic-analysis/2-testing/sum/sum_test.go | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/3-dynamic-analysis/2-testing/sum/sum_test.go b/3-dynamic-analysis/2-testing/sum/sum_test.go
index 6475a09..a737f09 100644
--- a/3-dynamic-analysis/2-testing/sum/sum_test.go
+++ b/3-dynamic-analysis/2-testing/sum/sum_test.go
@@ -22,4 +22,6 @@ import (
 
 func TestAll(t *testing.T) {
 	// Implement the body of this test, calling sum.All.
+
+	_ = sum.All
 }
```

This other one is perhaps a bit easier to understand, though it makes me want to have a more complete body for the test.

What do you think?

**Comment by campoy** [comment]
Hey, thanks for the PR but this makes the code be invalid which makes a lot of my tests fail apparently ...

Maybe you could just add a comment out import and a comment on top telling what that is for?

**Comment by inkel** [comment]
Yeah, I realized I broke everything yeeey. Sorry about that.

You mean adding something like:

```go
import (
  "testing"

  // Uncomment the following line to import the exported methods of sum as part of this package (i.e. no need to prefix with `sum.`, you can call All directly)
  // . "github.com/campoy/go-tooling-workshop/3-dynamic-analysis/2-testing/sum"

  // Or uncomment the following line to import `sum` as a regular package, thus accessing the exported values like `sum.All`.
  // "github.com/campoy/go-tooling-workshop/3-dynamic-analysis/2-testing/sum"
)
```

?

**Comment by campoy** [comment]
I think it's better to leave this as-is.
People will be using goimports so it's not a big issue.

**Pull request closed without merging**
